[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "neatpush"
authors = [
    {name = "Guillaume Jeusel", email = "jeusel.guillaume@gmail.com"},
]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.10"
dynamic = ["version", "description"]


dependencies = [
  'typer',
  'uvloop',
  'pydantic[dotenv]',

  # scraping:
  'httpx',
  'gazpacho',  # html parsing - easier than beautiful soup
  'dateparser',  # parse human readable dates

  # task queue:
  'arq==0.23a1',
  'aioredis==2.0.1',
  'orjson',
  'watchgod',  # watch file change for arq

  # logs:
  'structlog',
  'rich',  # add exceptions ftm to structlog

  # edgedb:
  # 'edgedb==0.24.0a5',  # not yet available, in the meantime:
  # pip install git+https://github.com/edgedb/edgedb-python@14f8a32ca415fee1219d62343cfbca239eaa12d1

  'edgeql-queries==0.4.0',  # https://github.com/nsidnev/edgeql-queries
]

[project.optional-dependencies]
qa = [
  'flake8',
  'flake8-bugbear',
  'flake8-builtins',
  'black',
  'isort',
  'pre-commit',
]

test = [
  'coverage>=5.0.3',
  'pytest',
  'pytest-asyncio',
  'vcrpy',
]

[project.scripts]
neatpush = "neatpush.__main__:cli"

[tool.isort]
line_length = 88
profile = 'black'

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
(
  /(
    \.git
    | \.mypy_cache
    | \.pytest_cache
    | htmlcov
    | build
  )/
)
'''

[tool.mypy]
python_version = 3.10

ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_configs = true
show_column_numbers = true

disallow_subclassing_any = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = false

no_implicit_optional = true
warn_unused_ignores = true
warn_return_any = true
strict_equality = true

[[tool.mypy.overrides]]
module = ['tests.*']
disallow_subclassing_any = false
disallow_untyped_defs = false
disallow_untyped_calls = false
disallow_incomplete_defs = false
disallow_untyped_decorators = false

[tool.pytest.ini_options]
asyncio_mode = 'auto'
