[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "neatpush"
authors = [
    {name = "Guillaume Jeusel", email = "jeusel.guillaume@gmail.com"},
]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.10"
dynamic = ["version", "description"]


dependencies = [
  'typer',
  'uvloop',
  'pydantic[dotenv]',

  # scraping:
  'httpx',
  'gazpacho',  # html parsing - easier than beautiful soup
  'dateparser',  # parse human readable dates

  # task queue:
  'arq==0.23a1',
  'aioredis==2.0.1',
  'orjson',
  'watchgod',  # watch file change for arq

  # logs:
  'structlog',
  'rich',  # add exceptions ftm to structlog

  # db:
  'prisma',
]

[project.optional-dependencies]
qa = [
  'flake8',
  'flake8-bugbear',
  'flake8-builtins',
  'black',
  'isort',
  'pre-commit',
]

test = [
  'coverage>=5.0.3',
  'pytest',
  'pytest-asyncio',
  'vcrpy',
]

[project.scripts]
neatpush = "neatpush.__main__:cli"

[tool.isort]
line_length = 88
profile = 'black'

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
(
  /(
    \.git
    | \.mypy_cache
    | \.pytest_cache
    | htmlcov
    | build
  )/
)
'''

[tool.pyright]
typeCheckingMode = "strict"
reportMissingImports = true
reportMissingTypeStubs = false
reportIncompatibleVariableOverride = false  # class Config in pydantic
reportPrivateImportUsage = false  # arq.ArqRedis (not in __all__)

[tool.pytest.ini_options]
asyncio_mode = 'auto'
