"""initial migration

Revision ID: aa0ce1324fa4
Revises: 
Create Date: 2022-07-17 07:22:41.277046+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "aa0ce1324fa4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("Manga_name_key", table_name="Manga")
    op.drop_table("Manga")
    op.drop_index("MangaChapter_mangaId_key", table_name="MangaChapter")
    op.drop_table("MangaChapter")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "MangaChapter",
        sa.Column("id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("num", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(precision=3),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "notified",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("mangaId", sa.TEXT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["mangaId"],
            ["Manga.id"],
            name="MangaChapter_mangaId_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="MangaChapter_pkey"),
    )
    op.create_index(
        "MangaChapter_mangaId_key", "MangaChapter", ["mangaId"], unique=False
    )
    op.create_table(
        "Manga",
        sa.Column("id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="Manga_pkey"),
    )
    op.create_index("Manga_name_key", "Manga", ["name"], unique=False)
    # ### end Alembic commands ###
